
package com.cesar;

import com.cesar.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CadastroProviderService", targetNamespace = "http://cesar.com/", wsdlLocation = "http://localhost:8080/WebService/CadastroProvider?wsdl")
public class CadastroProviderService
    extends Service
{

    private final static URL CADASTROPROVIDERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.cesar.CadastroProviderService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.cesar.CadastroProviderService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/WebService/CadastroProvider?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/WebService/CadastroProvider?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CADASTROPROVIDERSERVICE_WSDL_LOCATION = url;
    }

    public CadastroProviderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CadastroProviderService() {
        super(CADASTROPROVIDERSERVICE_WSDL_LOCATION, new QName("http://cesar.com/", "CadastroProviderService"));
    }

    /**
     * 
     * @return
     *     returns CadastroProvider
     */
    @WebEndpoint(name = "CadastroProviderPort")
    public CadastroProvider getCadastroProviderPort() {
        return super.getPort(new QName("http://cesar.com/", "CadastroProviderPort"), CadastroProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CadastroProvider
     */
    @WebEndpoint(name = "CadastroProviderPort")
    public CadastroProvider getCadastroProviderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cesar.com/", "CadastroProviderPort"), CadastroProvider.class, features);
    }

}
