
package com.cesar;

import com.cesar.*;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CadastroProvider", targetNamespace = "http://cesar.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CadastroProvider {


    /**
     * 
     * @param fornecedor
     * @return
     *     returns com.cesar.Retorno
     */
    @WebMethod
    @WebResult(partName = "return")
    public Retorno cadFornecedor(
        @WebParam(name = "fornecedor", partName = "fornecedor")
        Fornecedor fornecedor);

}
